spring: 
  profiles: 
  active:
  - dev

--- 
spring:
  profiles:dev
  application:
    name:  springcloud-config-jd-dev

--- 
spring:
  profiles:test
  application:
    name:  springcloud-config-jd-test
